[package]
name = "thread_sync"
version = "0.1.0"
authors = ["chengxd <chengxd@wondershare.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gettid = "0.1.2"