[package]
name = "mio_echo"
version = "0.1.0"
authors = ["chengxd <chengxd@wondershare.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
mio = { version = "0.7.0", features = ["os-poll", "tcp"] }
