[package]
name = "rust_2018"
version = "0.1.0"
authors = ["chengxd <chengxd@wondershare.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }